
-- ==========================================
-- 1. SETUP TABLES (Safe to run multiple times)
-- ==========================================

-- USERS
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text default 'Donor', -- Donor, Volunteer, NGO
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REPORTS (Needy People)
create table if not exists public.reports (
    id bigint generated by default as identity primary key,
    image_url text not null,
    latitude double precision not null,
    longitude double precision not null,
    description text,
    status text default 'open', -- open, verified, resolved
    urgency text default 'medium', -- low, medium, high
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TASKS (Missions for Volunteers)
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text, -- pickup, delivery, verification
    latitude double precision,
    longitude double precision,
    points integer default 10,
    status text default 'pending', -- pending, accepted, completed
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- DONATIONS
create table if not exists public.donations (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    category text, 
    status text default 'available',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ENABLE RLS (Security)
alter table public.users enable row level security;
alter table public.reports enable row level security;
alter table public.tasks enable row level security;
alter table public.donations enable row level security;

-- OPEN POLICIES (For Demo Ease - Access for All)
create policy "Public Access Users" on public.users for select using (true);
create policy "Public Access Reports" on public.reports for select using (true);
create policy "Public Access Reports Insert" on public.reports for insert with check (true);
create policy "Public Access Tasks" on public.tasks for select using (true);
create policy "Public Access Tasks Insert" on public.tasks for insert with check (true);
create policy "Public Access Donations" on public.donations for select using (true);


-- ==========================================
-- 2. INSERT INDIAN DEMO DATA
-- ==========================================

-- Dummy Tasks for Volunteers (Using Lat/Long for major Indian Cities or Generic)
INSERT INTO public.tasks (title, description, type, latitude, longitude, points, status)
VALUES 
('Food Pickup at Connaught Place', 'Pickup 20 meals from Haldirams for distribution.', 'pickup', 28.6304, 77.2177, 50, 'pending'),
('Medicine Delivery to Grandma', 'Deliver insulin to Mrs. Sharma in Lajpat Nagar.', 'delivery', 28.5685, 77.2408, 100, 'pending'),
('Blanket Drive in Karol Bagh', 'Distribute 50 blankets to homeless shelter.', 'verification', 28.6520, 77.1910, 30, 'pending'),
('Teaching Kids at NGO', 'Teach basic math to 10 kids at Hope Foundation, Mumbai.', 'volunteering', 19.0760, 72.8777, 150, 'pending'),
('Stray Dog Feeding', 'Feed street dogs in Indiranagar, Bangalore.', 'volunteering', 12.9716, 77.5946, 20, 'pending');

-- Dummy Reports of Needy People (Geo-Tagged)
INSERT INTO public.reports (image_url, description, latitude, longitude, urgency, status)
VALUES
('https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80', 'Homeless family needs winter clothes near Railway Station.', 28.6100, 77.2300, 'high', 'open'),
('https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80', 'Elderly man needs food in Sector 18 park.', 28.5700, 77.3200, 'medium', 'verified');

-- Dummy Donations (Available Items)
INSERT INTO public.donations (title, description, category, status)
VALUES
('Rice Bags (5kg)', 'Basmati rice surplus from wedding.', 'Food', 'available'),
('School Books (Class 10)', 'Old NCERT books for donation.', 'Education', 'available'),
('Boys Winter Jacket', 'Size M, slightly used but good condition.', 'Clothes', 'available');

-- Note: We generally don't insert Users directly here because they are linked to Auth. 
-- But this data will populate the Dashboard immediately!
