
-- =================================================================================
-- FINAL RESET SCRIPT: NUKE & REBUILD
-- This script DELETES ALL DATA AND TABLES and recreates them from scratch.
-- RUN THIS ONCE TO FIX EVERYTHING.
-- =================================================================================

-- 1. NUKE EVERYTHING (Drop tables safely)
-- We use CASCADE to remove dependent policies and keys automatically.
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.donations CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. RE-CREATE TABLES

-- USERS
CREATE TABLE public.users (
  id uuid PRIMARY KEY, -- Linked loosely to Auth
  email text,
  name text,
  role text DEFAULT 'Donor', -- Donor, Volunteer, NGO
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- MESSAGES
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstName text,
  lastName text,
  email text,
  message text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- DONATIONS
CREATE TABLE public.donations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id uuid REFERENCES public.users(id),
    title text NOT NULL,
    description text,
    category text, 
    quantity text,
    pickup_address text,
    status text DEFAULT 'available',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- REPORTS
CREATE TABLE public.reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id uuid REFERENCES public.users(id),
    image_url text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    description text,
    status text DEFAULT 'open',
    urgency text DEFAULT 'medium',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TASKS
CREATE TABLE public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    type text,
    latitude double precision,
    longitude double precision,
    points integer DEFAULT 10,
    status text DEFAULT 'pending',
    assigned_to uuid REFERENCES public.users(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE SECURITY (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICIES (Simple & Open for Demo)
-- Users
CREATE POLICY "Public Read Users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Auth Insert Users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Auth Update Users" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Messages
CREATE POLICY "Public Read Messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Public Insert Messages" ON public.messages FOR INSERT WITH CHECK (true);

-- Donations
CREATE POLICY "Public Read Donations" ON public.donations FOR SELECT USING (true);
CREATE POLICY "Auth Insert Donations" ON public.donations FOR INSERT WITH CHECK (true);
CREATE POLICY "Auth Update Donations" ON public.donations FOR UPDATE USING (true);

-- Reports
CREATE POLICY "Public Read Reports" ON public.reports FOR SELECT USING (true);
CREATE POLICY "Auth Insert Reports" ON public.reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Auth Update Reports" ON public.reports FOR UPDATE USING (true);

-- Tasks
CREATE POLICY "Public Read Tasks" ON public.tasks FOR SELECT USING (true);
CREATE POLICY "Auth Insert Tasks" ON public.tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Auth Update Tasks" ON public.tasks FOR UPDATE USING (true);


-- 5. INSERT INDIAN DEMO DATA

-- Users (Mock IDs)
INSERT INTO public.users (id, email, name, role) VALUES 
('d0c2c0e0-0000-0000-0000-000000000001', 'admin@ngo.org', 'Aditi Rao (Admin)', 'NGO'),
('d0c2c0e0-0000-0000-0000-000000000002', 'rahul@volunteer.com', 'Rahul Sharma', 'Volunteer'),
('d0c2c0e0-0000-0000-0000-000000000003', 'priya@donor.com', 'Priya Verma', 'Donor'),
('d0c2c0e0-0000-0000-0000-000000000004', 'vikram@volunteer.com', 'Vikram Singh', 'Volunteer'),
('d0c2c0e0-0000-0000-0000-000000000005', 'sneha@donor.com', 'Sneha Gupta', 'Donor');

-- Donations (Linked to Donors)
INSERT INTO public.donations (donor_id, title, description, category, quantity, pickup_address, status) VALUES 
('d0c2c0e0-0000-0000-0000-000000000003', 'Rice Bags (5kg)', 'Basmati rice surplus from wedding function.', 'Food', '10 Bags', 'Sector 18, Noida', 'available'),
('d0c2c0e0-0000-0000-0000-000000000003', 'School Books (Class 10)', 'Old NCERT books (Maths, Science) for donation.', 'Education', '15 Sets', 'Lajpat Nagar, Delhi', 'available'),
('d0c2c0e0-0000-0000-0000-000000000005', 'Men Winter Jackets', 'Size M & L, slightly used but dry cleaned.', 'Clothes', '5 Jackets', 'MG Road, Gurgaon', 'available'),
('d0c2c0e0-0000-0000-0000-000000000005', 'Woolen Blankets', 'New blankets for winter drive.', 'Essentials', '50 Pcs', 'Chandni Chowk, Delhi', 'pledged');

-- Reports (Linked to Reporters)
INSERT INTO public.reports (reporter_id, image_url, description, latitude, longitude, urgency, status) VALUES
('d0c2c0e0-0000-0000-0000-000000000003', 'https://images.unsplash.com/photo-1541976844346-a6a8d660f9d1?auto=format&fit=crop&w=800&q=80', 'Slum children need basic study materials (notebooks, pencils).', 28.6129, 77.2293, 'low', 'open'),
('d0c2c0e0-0000-0000-0000-000000000003', 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80', 'Homeless family with small kids needs winter blankets.', 28.6328, 77.2197, 'high', 'open'),
('d0c2c0e0-0000-0000-0000-000000000005', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80', 'Elderly man living alone needs weekly food ration support.', 28.5677, 77.2433, 'medium', 'verified');

-- Tasks (Volunteer Missions)
INSERT INTO public.tasks (title, description, type, latitude, longitude, points, status, assigned_to) VALUES 
('Food Pickup at Haldirams', 'Pickup 20 packaged meals and deliver to Shelter A.', 'pickup', 28.6304, 77.2177, 50, 'pending', NULL),
('Medicine Drop: Insulin', 'Urgent insulin delivery to Mrs. Sharma (Senior Citizen).', 'delivery', 28.5685, 77.2408, 100, 'pending', NULL),
('Verify Needy Report #12', 'Go to location and verify if family still needs blankets.', 'verification', 28.6520, 77.1910, 30, 'assigned', 'd0c2c0e0-0000-0000-0000-000000000002'),
('Teach Math: Weekend Class', 'Volunteer needed to teach basic math to 10 kids at Hope Center.', 'volunteering', 28.5244, 77.1855, 150, 'pending', NULL),
('Stray Dog Feeding Drive', 'Join the team to feed street dogs in Indiranagar sector.', 'volunteering', 28.6400, 77.2200, 20, 'pending', NULL);

-- Messages
INSERT INTO public.messages (firstName, lastName, email, message) VALUES 
('Rohan', 'Das', 'rohan.d@gmail.com', 'I have a van and can help with bulk food transport on weekends.'),
('Anjali', 'Mehta', 'anjali.m@corporate.com', 'Our company wants to sponsor 100 school kits. Please contact us.');

