
-- 1. Create Users Table (extends default Auth)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Messages Table (for Contact Form)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  firstName text,
  lastName text,
  email text,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Donations Table
create table if not exists public.donations (
    id bigint generated by default as identity primary key,
    donor_id uuid references public.users(id),
    title text not null,
    description text,
    category text, -- Food, Clothes, etc.
    quantity text,
    pickup_address text,
    status text default 'available', -- available, pledged, collected
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table public.users enable row level security;
alter table public.messages enable row level security;
alter table public.donations enable row level security;

-- 5. Policies

-- Users: Everyone can read basic profiles (names/roles)
create policy "Public profiles are viewable by everyone." 
on public.users for select 
using ( true );

-- Users: Only the user can update their own profile
create policy "Users can update own profile." 
on public.users for update 
using ( auth.uid() = id );

-- Users: Users can insert their own profile on signup
create policy "Users can insert their own profile." 
on public.users for insert 
with check ( auth.uid() = id );

-- Messages: Anyone can insert (contact form is public)
create policy "Anyone can send messages" 
on public.messages for insert 
with check ( true );

-- Donations: Anyone can read available donations
create policy "Donations are viewable by everyone." 
on public.donations for select 
using ( true );

-- Donations: Logged in users can create donations
create policy "Authenticated users can create donations." 
on public.donations for insert 
with check ( auth.role() = 'authenticated' );

-- Donations: Donors can update their own donations
create policy "Donors can update own donations." 
on public.donations for update 
using ( auth.uid() = donor_id );
