
-- Keep existing tables (Users, Messages, Donations) from previous run
-- If they exist, these commands will just skip or error safely if you use "if not exists"

-- 1. Create Reports Table (Geo-Tagged Needy Reports)
create table if not exists public.reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid references public.users(id),
    image_url text not null,
    latitude double precision not null,
    longitude double precision not null,
    description text,
    status text default 'open', -- open, verified, resolved
    urgency text default 'medium', -- low, medium, high
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Tasks Table (For Volunteers)
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text, -- pickup, delivery, verification
    latitude double precision,
    longitude double precision,
    points integer default 10,
    status text default 'pending', -- pending, assigned, completed
    assigned_to uuid references public.users(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.reports enable row level security;
alter table public.tasks enable row level security;

-- 4. Policies for Reports
create policy "Anyone can read reports" on public.reports for select using ( true );
create policy "Authenticated users can create reports" on public.reports for insert with check ( auth.role() = 'authenticated' );

-- 5. Policies for Tasks
create policy "Anyone can read tasks" on public.tasks for select using ( true );
create policy "Volunteers can update tasks" on public.tasks for update using ( auth.role() = 'authenticated' );

-- 6. Storage Buckets (Execute this in SQL Editor, though buckets usually need UI creation)
-- Note: You generally have to create a bucket named 'reports' in the Storage section of Supabase Dashboard manually.
-- This SQL attempts to insert into the storage.buckets table if you have permissions, but UI is safer.
insert into storage.buckets (id, name, public) 
values ('reports', 'reports', true)
on conflict (id) do nothing;

-- Allow public read of reports bucket
create policy "Public Access" on storage.objects for select
using ( bucket_id = 'reports' );

-- Allow authenticated upload
create policy "Authenticated Upload" on storage.objects for insert
with check ( bucket_id = 'reports' and auth.role() = 'authenticated' );
